config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  get 'history', to: 'comments#history'
  devise_for :users
  root 'posts#index'
  get 'search', to: 'posts#search'
  get 'about', to: 'pages#about'
  resources :contacts, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  before_create :set_comment_number
  has_rich_text :body

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  private

  def set_comment_number
    self.comment_number = user.comment_created
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Comments Controller class
class CommentsController < ApplicationController
  before_action :find_commentable, only: [:create]
  before_action :set_comment, except: [:create]
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.user = current_user
    @comment.reply = true if params[:comment_id]
    @comment.save
  end

  def edit; end

  def update
    puts('line before')
    puts(@comment.edit_history)
    puts('line after')
    @comment.edit_history = if @comment.edit_history.to_s == ''
                              puts('Went into first')
                              'Original: ' + @comment.body.body.to_plain_text + '☠'
                            else
                              puts('Went into second')
                              @comment.edit_history + 'Edit: ' + params[:comment][:body] + '☠'
                            end
    @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  def history; end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    # Comment
    if params[:comment_id]
      @commentable = Comment.find_by_id(params[:comment_id])
    elsif params[:post_id]
      @commentable = Post.friendly.find(params[:post_id])
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-container" id="comment-<%= comment.id %>">
  <div class="container">
    <%= render 'comments/comments', comment: comment, local: Comment.new %>

    <% unless comment.reply %>
      <div class="row">
        <div class="col-4">
        </div>
        <div class="col-8">
          <div class="comment-form-nested">
            <%= render 'comments/form', commentable: comment, local: Comment.new %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-3">
    <div class="row">
      <% if comment.user.avatar.attached? %>
        <%= image_tag(comment.user.avatar, class: 'comment-avatar') %>
      <% else %>
        <%= image_tag("/empty_avatar.png", class: 'comment-avatar') %>
      <% end %>
    </div>
    <div class="row">
      <div class="comment-timestamp" id="edit-history-text-<%= comment.id %>">
        <%= render 'comments/edit_history_text', comment: comment %>
      </div>
    </div>
  </div>
  <div class="col-9">
    <div class="row">
      <div class="col-8">
        <div class="comment-username">
          <%= comment.user.username %>
        </div>
        <div class="comment-number">
          #<%= comment.comment_number %>
        </div>
      </div>
      <% if current_user && (current_user == comment.user || current_user.admin) %>
        <div class="col-4 text-right" style="padding-right: 0;">
          <div class="button-group" role="group" aria-label="Edit and Delete Button Group">
            <%= link_to "Edit", edit_comment_path(comment), class: 'btn btn-warning', remote: true %>
            <%= link_to "Delete", comment, class: 'btn btn-danger', method: :delete, remote: true %>
          </div>
        </div>
      <% end %>
    </div>
    <hr class="md-4">
    <div class="comment-body" id="comment-body-<%= comment.id %>">
      <%= comment.body %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-3">
  </div>
  <div class="col-9">
    <div class="inner-comment-container" id="reply-<%= comment.id %>">
      <% comment.comments.each do |comment| %>
        <%= render comment %>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="edit_history" tabindex="-1" role="dialog" aria-labelledby="Comment Edit History" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="edit_history_title">
          Edit History
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            &times;
          </span>
        </button>
      </div>
      <div class="modal-body" id="edit-history-body">
        <%= render 'comments/edit_history', comment: comment %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>

app/views/comments/_edit_history.html.erb
<%= comment.edit_history&.gsub('☠', '<br/><hr/>')&.html_safe %>
<% puts("OOOOOOOOOOOO") %>

<%#= comment.edit_history&.gsub(/\n/, '<br/><hr/>').to_s.html_safe %>

app/views/comments/_edit_history_text.html.erb
<%= time_ago_in_words(comment.created_at) %> ago
<br/>
<% edit_history = comment.edit_history == '' ? '' : 'Last edit ' + time_ago_in_words(comment.updated_at) + ' ago' %>
<%= link_to(edit_history, 'javascript:;', data: {toggle: 'modal', target: '#edit_history'}) %>

app/views/comments/_form.html.erb
<% if current_user %>
  <div class="row">
    <div class="comment-form">
      <%= form_with model: [commentable, local] do |f| %>
        <div class="form-group">
          <%= f.rich_text_area :body, placeholder: "Say something...", class: "reply-form-#{commentable.id}", id: f.object.object_id, method: :patch %>
          <%= f.submit "Post", class: 'btn btn-dark float-right' %>
        </div>
      <% end %>
    </div>
  </div>

  <script>
      $(document).on("turbolinks:load", function () {
          $(".trix-button-group--file-tools").remove();
          document.addEventListener("trix-file-accept", function (event) {
              event.preventDefault();
          });
      });
  </script>

<% else %>
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-8">
      <h2 class="comment-login-prompt"><%= link_to "Login", new_user_session_path %> to comment</h2>
    </div>
    <div class="col-2"></div>
  </div>
<% end %>

app/views/comments/create.js.erb
if ("<%= @comment.reply %>" === 'true') {
    let comment_pane;

    if ("<%= @commentable.comments.count %>" === "0") {
        comment_pane = "#reply-container-<%=@commentable.id %>";
    } else {
        comment_pane = "#reply-<%=@comment.commentable_id %>";
    }

    $(comment_pane).append("<%= j render @comment %>");
    $(".reply-form-<%= @commentable.id %>").val('');
} else {
    $("#comment-pane").prepend("<%= j render @comment %>");
    $(".reply-form-<%= @commentable.id %>").val('');
}
$('.trix-button-group--file-tools').remove();

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/comments/edit.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= j render 'comments/form', commentable: @comment.commentable, local: @comment %>");
$(".trix-button-group--file-tools").remove();

app/views/comments/update.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= raw @comment.body.body.to_html %>");

$("#edit-history-body").html("<%= j render 'comments/edit_history', comment: @comment %>");

$("#edit-history-text-<%= @comment.id %>").html("<%= j render 'comments/edit_history_text', comment: @comment %>");