config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  get 'history', to: 'comments#history'
  devise_for :users
  root 'posts#index'
  get 'search', to: 'posts#search'
  get 'about', to: 'pages#about'
  resources :contacts, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :commentable, dependent: :destroy

  has_one_attached :thumbnail
  has_one_attached :banner
  has_rich_text :body

  validates :title, length: { minimum: 5 }
  validates :body, length: { minimum: 25 }

  self.per_page = 10
  extend FriendlyId
  friendly_id :title, use: :slugged

  def optimized_image(image, x, y)
    image.variant(resize_to_fill: [x, y]).processed
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Post Controller class
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show search]
  before_action :is_admin!, except: %i[index show search]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page])
  end

  def search
    @posts = Post.where('lower(title) LIKE ?', '%' + params[:q].to_s.downcase + '%').order('created_at DESC').paginate(page: params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
    @comments = @post.comments.order('created_at DESC')
    @num_comments = @post.comments.count
    @post.comments.each do |comment|
      @num_comments += comment.comments.count
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :thumbnail, :banner)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>

  <div class="form-inputs">
    <%= f.text_field :title, class: 'form-control string', required: true %>
    <%= f.label :thumbnail, class: 'form-control' %>
    <%= f.file_field :thumbnail, required: true %>
    <%= f.label :banner, class: 'form-control' %>
    <%= f.file_field :banner, required: true %>
    <%= f.rich_text_area :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="digg_pagination">
      <%= will_paginate(@posts, :container => false) %>
    </div>
  </div>


  <% @posts.each do |post| %>
    <div class="row">
      <div class="card mb-3">
        <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>" alt="Blog Post Image Card"/>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to post.title, post %>
          </h5>
          <p class="card-text">
            <%= post.body.to_plain_text.truncate_words(50) %>
          </p>
          <p class="card-text">
            <small class="text-muted">
              <%= post.updated_at.strftime("%A, %B %e, %Y") %> by
              <%= post.user.username %> | <%= pluralize(post.views, "View") %> |
              <% @num_comments = post.comments.count %>
              <% post.comments.each do |comment| %>
                <% @num_comments += comment.comments.count %>
              <% end %>

              <%= pluralize(@num_comments, "Comment") %> |
              <% if current_user && (current_user.admin || current_user == post.user) %>
                <%= link_to "Delete", post, method: :delete %>
              <% end %>
            </small>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: 'btn btn-outline-success my-4' %>

app/views/posts/search.erb
<h1>Search results</h1>
<div class="container">
  <div class="row">
    <div class="digg_pagination">
      <%= will_paginate(@posts, :container => false) %>
    </div>
  </div>

  <% if @posts.first == nil %>
    <p class="lead">
      No posts found, whose title would match your query. </p>
  <% end %>

  <% @posts.each do |post| %>
    <div class="row">
      <div class="card mb-3">
        <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>" alt="Blog Post Image Card"/>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to post.title, post %>
          </h5>
          <p class="card-text">
            <%= post.body.to_plain_text.truncate_words(50) %>
          </p>
          <p class="card-text">
            <small class="text-muted">
              <%= post.updated_at.strftime("%A, %B %e, %Y") %> by
              <%= post.user.username %> | <%= pluralize(post.views, "View") %> |
              <% @num_comments = post.comments.count %>
              <% post.comments.each do |comment| %>
                <% @num_comments += comment.comments.count %>
              <% end %>

              <%= pluralize(@num_comments, "Comment") %> |
              <% if current_user && (current_user.admin || current_user == post.user) %>
                <%= link_to "Delete", post, method: :delete %>
              <% end %>
            </small>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div style="width:100%; height: 300px; overflow-y:hidden">
  <%= image_tag(@post.banner, style: 'width:100%') %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width:100%">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.username %>
        | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4"/>
      <div class="post_body">
        <%= @post.body %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <%= render 'comments/form', commentable: @post, local: Comment.new %>

  <div id="comment-pane">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  </div>
</div>