config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  get 'history', to: 'comments#history'
  devise_for :users
  root 'posts#index'
  get 'search', to: 'posts#search'
  get 'about', to: 'pages#about'
  resources :contacts, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= image_tag("logo.png", class: "img-responsive", :size => "30x30", id: "navbar-logo") %>
  <%= link_to "Final Project", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="<%= current_page?(root_path) ? 'nav-item active' : 'nav-item' %>">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="<%= current_page?(about_path) ? 'nav-item active' : 'nav-item' %>">
        <a class="nav-link" href="<%= about_path %> ">About</a>
      </li>
      <li class="<%= current_page?(new_contact_path) ? 'nav-item active' : 'nav-item' %>">
        <a class="nav-link" href="<%= new_contact_path %> ">Contact me</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">

      <%= form_tag(search_path, method: 'get', class: 'form-inline') do %>
        <%= search_field_tag 'q', nil, class: 'form-control mr-sm-2', placeholder: 'Search', required: true %>
        <%= submit_tag "Submit", class: 'btn btn-outline-success my-2 my-sm-0 mr-sm-4', :name => nil %>
      <% end %>

      <% if current_user %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.admin %>
              <a class="dropdown-item" href="<%= new_post_path %>">New Post</a>
            <% end %>
            <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Signup", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Signin", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Project</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application" %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

<%= render 'layouts/navbar' %>
<div class="container">
  <br><br>

  <%= yield %>
</div>

<div class="container">
  <footer class="footer">
    <small>
      © 2019 <a href="http://www.wtfpl.net/">WTFPL</a> – Do What the Fuck You Want to Public License.
    </small>
  </footer>
</div>


</body>
</html>